name: RDP-Tailscale
on: workflow_dispatch
jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-LocalUser -Name runneradmin -Password (ConvertTo-SecureString -AsPlainText "${{ secrets.RDP_PASSWORD }}" -Force)

      - name: Connect Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}
          hostname: gh-rdp

      - name: Show IP
        run: tailscale ip -4

      - name: Keep alive
        run: Start-Sleep -Seconds 21000
